x-superset-user: &superset-user root
x-superset-volumes: &superset-volumes
  # /app/pythonpath_docker will be appended to the PYTHONPATH in the final container
  - ./docker:/app/docker
  - ./superset:/app/superset
  - ./docker/superset_config.py:/app/pythonpath/superset_config.py

services:
  db:
    container_name: postgres_container
    image: postgres:14.22
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/airflow_init.sh:/docker-entrypoint-initdb.d/airflow_init.sh
      - ./postgres/superset_init.sql:/docker-entrypoint-initdb.d/superset_init.sql
    env_file:
      - .env
    networks:
      - my-network
  
  af:
    container_name: airflow_container
    image: apache/airflow:3.0.0
    ports:
      - 8080:8080
    command: >
      bash -c "airflow db migrate && airflow standalone"
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:${AF_DB_PASSWORD}@${DB_NAME}:5432/airflow_db
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./.env:/opt/airflow/dags/.env
      - ./api-request:/opt/airflow/api-request
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - '1000'
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - my-network
  
  dbt:
    container_name: dbt_container
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
    volumes:
      - ./dbt/weather_data_project:/usr/app
      - ./dbt:/root/.dbt
    working_dir: /usr/app
    environment:
      DBT_PROFILES_DIR: "/root/.dbt"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - my-network
    command: run
  
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "127.0.0.1:${REDIS_PORT:-6379}:6379"
    volumes:
      - redis:/data
    networks:
      - my-network
  
  superset-init:
    image: apache/superset:3.0.0-py310
    container_name: superset_init
    command: ["/app/docker/docker-init.sh"]
    env_file:
      - path: docker/.env
        required: true
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    user: *superset-user
    volumes: *superset-volumes
    environment:
      SUPERSET_LOAD_EXAMPLES: "${SUPERSET_LOAD_EXAMPLES:-yes}"
      SUPERSET_LOG_LEVEL: "${SUPERSET_LOG_LEVEL:-info}"
      DATABASE_DB: "${POSTGRES_DB}"
    healthcheck:
      disable: true
    networks:
      - my-network
  
  superset:
    env_file:
      - path: docker/.env
        required: true
    image: apache/superset:3.0.0-py310
    container_name: superset_app
    command: ["/app/docker/docker-bootstrap.sh", "app"]
    restart: unless-stopped
    ports:
      - ${SUPERSET_PORT:-8088}:8088
    user: *superset-user
    depends_on:
      superset-init:
        condition: service_completed_successfully
    volumes: *superset-volumes
    environment:
      SUPERSET_LOG_LEVEL: "${SUPERSET_LOG_LEVEL:-info}"
      DATABASE_DB: "${POSTGRES_DB}"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  redis:
    external: false